Blur filter
ndreuu/HomeWorks pull request #3
Opened 2020-11-21 20:17 UTC by AndrewOleynikov

2020-12-16 20:51 UTC, Maksim-Zhuravlev requested changes
Стиль.
Возможно логическая ошибка.
И проверьте код в целом. Ускорение сликом незначительное. В этой задаче оно должно достигаться.

2020-12-16 20:51 UTC, Maksim-Zhuravlev commented on Blur/src/main/java/main/BlurFilter.java
> +public class BlurFilter extends Thread{
Пробел

2020-12-16 20:51 UTC, Maksim-Zhuravlev commented on Blur/src/main/java/main/BlurThreads.java
> +            if (i == countOfThreads - 1) {
Уверены в корректности условия?
Сравниваете номер столбца с номером потока.

2020-12-16 21:07 UTC, AndrewOleynikov commented on Blur/src/main/java/main/BlurThreads.java
> +            if (i == countOfThreads - 1) {
Это же для вертикального алгоритма, тут сравнивается номер потока и вертикальный кусок изображения - столбец

2020-12-16 21:09 UTC, AndrewOleynikov commented on Blur/src/main/java/main/BlurThreads.java
> +            if (i == countOfThreads - 1) {
А потом применяется размытие по этому куску начиная сверху и заканчивая пикселями в самом низу

2020-12-19 21:22 UTC, Maksim-Zhuravlev commented on Blur/src/main/java/main/BlurThreads.java
> +            if (i == countOfThreads - 1) {
Возможно, вы правы, но что вижу я, читая по-диагонали:
i меняется от 0 до width с шагом step.
Ширина картинки, скажем, 1024 пикселя, количество потоков - 8.
Тогда step = 128. Значения i - {0, 128, 256, ..., 896}.
countOThreads - 1 будет в моем примере 7. На ноутбуках нынешних студентов 3, 7, 11, 15, предполагая количество потоков равным количеству физических или логических ядер.
Равенство значений практически недостижимо при случайном выборе картинки.

2023-01-07 21:34 UTC, merged